# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-01 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='share_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shares',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
